name: juicefs
version: 1.1.1
summary: Distributed POSIX file system built on top of Redis and S3.
description: |
  JuiceFS is a high-performance POSIX file system released
  under Apache License 2.0, particularly designed for the
  cloud-native environment. The data, stored via JuiceFS,
  will be persisted in Object Storage (e.g. Amazon S3), and
  the corresponding metadata can be persisted in various
  compatible database engines such as Redis, MySQL, and
  TiKV based on the scenarios and requirements.
confinement: strict
base: core22
grade: stable
architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]
parts:
  juicefs:
    source: https://github.com/juicedata/juicefs.git
    source-tag: v1.1.1
    plugin: make
    build-snaps: [go]
    override-build: |
      make
      cp $SNAPCRAFT_PART_BUILD/juicefs $SNAPCRAFT_PART_INSTALL
layout:
  /var/jfsCache:
    bind: $SNAP/var/jfsCache
apps:
  juicefs:
    command: juicefs
    plugs:
      - network
      - fuse-support
      - mount-observe
